/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DonatosRouteImport } from './routes/donatos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DonatosIndexRouteImport } from './routes/donatos/index'
import { Route as DonatosShopRouteImport } from './routes/donatos/shop'
import { Route as DonatosInventoryRouteImport } from './routes/donatos/inventory'
import { Route as DonatosActiveItemsRouteImport } from './routes/donatos/active-items'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'

const DonatosRoute = DonatosRouteImport.update({
  id: '/donatos',
  path: '/donatos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonatosIndexRoute = DonatosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DonatosRoute,
} as any)
const DonatosShopRoute = DonatosShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => DonatosRoute,
} as any)
const DonatosInventoryRoute = DonatosInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => DonatosRoute,
} as any)
const DonatosActiveItemsRoute = DonatosActiveItemsRouteImport.update({
  id: '/active-items',
  path: '/active-items',
  getParentRoute: () => DonatosRoute,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/donatos': typeof DonatosRouteWithChildren
  '/donatos/active-items': typeof DonatosActiveItemsRoute
  '/donatos/inventory': typeof DonatosInventoryRoute
  '/donatos/shop': typeof DonatosShopRoute
  '/donatos/': typeof DonatosIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/donatos/active-items': typeof DonatosActiveItemsRoute
  '/donatos/inventory': typeof DonatosInventoryRoute
  '/donatos/shop': typeof DonatosShopRoute
  '/donatos': typeof DonatosIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/donatos': typeof DonatosRouteWithChildren
  '/donatos/active-items': typeof DonatosActiveItemsRoute
  '/donatos/inventory': typeof DonatosInventoryRoute
  '/donatos/shop': typeof DonatosShopRoute
  '/donatos/': typeof DonatosIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/donatos'
    | '/donatos/active-items'
    | '/donatos/inventory'
    | '/donatos/shop'
    | '/donatos/'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/donatos/active-items'
    | '/donatos/inventory'
    | '/donatos/shop'
    | '/donatos'
    | '/demo/form/address'
    | '/demo/form/simple'
  id:
    | '__root__'
    | '/'
    | '/donatos'
    | '/donatos/active-items'
    | '/donatos/inventory'
    | '/donatos/shop'
    | '/donatos/'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DonatosRoute: typeof DonatosRouteWithChildren
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/donatos': {
      id: '/donatos'
      path: '/donatos'
      fullPath: '/donatos'
      preLoaderRoute: typeof DonatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donatos/': {
      id: '/donatos/'
      path: '/'
      fullPath: '/donatos/'
      preLoaderRoute: typeof DonatosIndexRouteImport
      parentRoute: typeof DonatosRoute
    }
    '/donatos/shop': {
      id: '/donatos/shop'
      path: '/shop'
      fullPath: '/donatos/shop'
      preLoaderRoute: typeof DonatosShopRouteImport
      parentRoute: typeof DonatosRoute
    }
    '/donatos/inventory': {
      id: '/donatos/inventory'
      path: '/inventory'
      fullPath: '/donatos/inventory'
      preLoaderRoute: typeof DonatosInventoryRouteImport
      parentRoute: typeof DonatosRoute
    }
    '/donatos/active-items': {
      id: '/donatos/active-items'
      path: '/active-items'
      fullPath: '/donatos/active-items'
      preLoaderRoute: typeof DonatosActiveItemsRouteImport
      parentRoute: typeof DonatosRoute
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DonatosRouteChildren {
  DonatosActiveItemsRoute: typeof DonatosActiveItemsRoute
  DonatosInventoryRoute: typeof DonatosInventoryRoute
  DonatosShopRoute: typeof DonatosShopRoute
  DonatosIndexRoute: typeof DonatosIndexRoute
}

const DonatosRouteChildren: DonatosRouteChildren = {
  DonatosActiveItemsRoute: DonatosActiveItemsRoute,
  DonatosInventoryRoute: DonatosInventoryRoute,
  DonatosShopRoute: DonatosShopRoute,
  DonatosIndexRoute: DonatosIndexRoute,
}

const DonatosRouteWithChildren =
  DonatosRoute._addFileChildren(DonatosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DonatosRoute: DonatosRouteWithChildren,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
